### ISSUE TITLE
Unable to Sync followed channels and games to Twitch

### ISSUE THREAD

**Issue by bmak6** [lindstrm/twitcha#14]
It says done but when I click on twitch it doesn't show anything there, weird.

**Comment by lindstrm** [comment]
Hmm.. just to clarify, did you click Channels under Manage follows or Twitch under settings?

**Comment by bmak6** [comment]
I'm clicking under "Manage Follows" after I've clicked "Sync Followed Channels" in Twitch Settings

**Comment by lindstrm** [comment]
Ok, thanks.

**Comment by bmak6** [comment]
Hmm unfortunately still unable to sync :(

Going to try and uninstall / remove all stuff in %appdata% then install again.

**Comment by bmak6** [comment]
Yeah no change, still having issues syncing follows.

**Comment by lindstrm** [comment]
Should hopefully be fixed with latest version.
