### ISSUE TITLE
VLC doesn't get opend

### ISSUE THREAD

**Issue by Linkshaender** [lindstrm/twitcha#16]
Hi There,

I just would like to report that VLC does not open when I click watch on a stream. I did install livestreamer and also entered the path to the exe where VLC is installed.

I have to admit I just found out about this Programm and I do not know if I did something wrong.

Best Regards

**Comment by lindstrm** [comment]
Hi!
Thanks for the report. I have noticed this as well one time and trying to reproduce the error.
In the mean time, just restart the twitcha.

Also, it uses VLC by default so no need to enter path to it.

**Comment by Linkshaender** [comment]
Hi,

so I restarted twitcha many times and it just worked once. I also restarted my pc a few times already and still nothing.
Just so you know everything that is happening.

But I really like the programm and the idea behind it. Im gonna wait for an update :D

Best Regards

**Comment by Linkshaender** [comment]
I would like to add something. There are some channels which get started but the channel "dota2ti" (for the dota 2 international) f.e. does not start even when I click on a lower resolution.

**Comment by ftmu** [comment]
i have same problem

**Comment by lindstrm** [comment]
Found the issue!
dota2ti have some new options on stream quality.

Thanks

**Comment by ftmu** [comment]
when u will update client?

**Comment by lindstrm** [comment]
Probably not today.
You can launch it manually by entering this in cmd;
c:\users\USERNAME\appdata\roaming\twitcha\livestreamer\livestreamer.exe twitch.tv/dota2ti 1080p60

just change username to your windows user.

**Comment by ftmu** [comment]
thanks

**Comment by Yofiee** [comment]
I have the same problem but when i try to enter the command you wrote above in cmd it first says 
"[cli][info] Found matching plugin twitch for URL twitch.tv/facittv" but the it says 
"error: Unable to open URL: https://api.twitch.tv/api/channels/facittv/access_token.json (400 Client Error: Bad Request)" and nothing happens

**Comment by lindstrm** [comment]
Fixed
