### ISSUE TITLE
Problem syncing my twich followers and wont launch channels anymore.

### ISSUE THREAD

**Issue by Shoelesshobo** [lindstrm/twitcha#17]
Recently (2 days ago) I have been unable to see my channels that I follow via twich and when I try to manually search and launch they don't launch. Going to try and delete and redownload to see if that fixes anything,

**Comment by lindstrm** [comment]
This has hopefully been fixed in next release.

**Comment by Shoelesshobo** [comment]
Yeah I read the other thread. Awesome thanks man love the app. Also thanks for the TI link so I can continue to watch it via VLC.

**Comment by lindstrm** [comment]
NP! Glad you like it :)
