### ISSUE TITLE
Sound Issue after skipping forward in VLC

### ISSUE THREAD

**Issue by finisaj** [lindstrm/twitcha#21]
Sound quality gets poor after you skip forward in VLC to decrease the stream delay. doesnt happen to me when starting a stream with livestreamer+vlc manually

**Comment by lindstrm** [comment]
Do you use any options when you start it manually?

**Comment by finisaj** [comment]
yeah --hls-segment-threads usually, looking forward to the implementation in twitcha :) im kinda clueless how this happen-s/ed, i think there was just some wierd thing going on, as i cant reproduce it today, but occured to me for a cpl of days before coming here (not using twitcha for long yet).

the sound kinda became like out of an old radio after the first skip forward, vlc wouldnt show me the bitrate so idk. really wierd.
