### ISSUE TITLE
Certain channels not launching.

### ISSUE THREAD

**Issue by Shoelesshobo** [lindstrm/twitcha#28]
I have noticed some of the channels I follow will not launch while others will. 

OS: Windows 10

**Comment by TENFIRE** [comment]
I found out that this problem has to do with some qualities on twitch.
Twitcha will only work when channels have these qualities "Source, High, Medium, Low, Mobile, Audio"
 but not qualities like: "720p60 or 1080p30"

The "Best" quality sent to livestreamer does not work with these qualities

**Comment by drjamiwe** [comment]
Can confirm. V. 2.1.10. 
livestream not able to start VLC with the given parameters

Windows 10 Professional x64

**Comment by BeBenNova** [comment]
This is now a widespread problem since Twitch allowed any partner to stream at 1080p 60fps so its no longer just tournament streams

**Comment by lindstrm** [comment]
Sorry for my absence, but i have "band-aid fixed" this in 2.1.11 for now. Meaning if you try to watch a stream that has these new qualities, it will pick the best quality automatically so you wont be able to choose a lower quality setting.
