### ISSUE TITLE
Some channels cant be opened with vlc !

### ISSUE THREAD

**Issue by littlebigboss** [lindstrm/twitcha#31]
at the moment i follow 31 channels and everything works great but for serveral days now some channels cant be opened with vlc

i click the "play" button in the channel preview window and then its greyed out but no vlc is starting
also the process "livestreamer.exe *32" is starting but no vlc

i tried to open them in different quality setting but no effect
if i start the channel with rightclick - open in browser ... it works fine

channels which are affected are "projectpt" "raizqt"

thx for help :)

**Comment by lindstrm** [comment]
This issue should be resolved now in 2.1.14

**Comment by littlebigboss** [comment]
can confirm ... channel "raizqt" works now (other streamer isnt online yet) ... thx :)

ps: i REALLY like your support of this tool *highfive
