### ISSUE TITLE
Clicking on Watch doesn't open VLC but gets stuck as if it did

### ISSUE THREAD

**Issue by BeBenNova** [lindstrm/twitcha#32]
Issue that started happening with the latest version, clicking a stream sometimes fails to open VLC and then gets stuck thinking it did open VLC and that you're watching it, leaving you unable to re-try unless you close down the entire app

I'm almost positive it's an issue with the new stream resolutions, the two streams it did in were 900p and then a really weird ultra widescreen resolution

**Comment by lindstrm** [comment]
Fixed in 2.1.15
