### ISSUE TITLE
Quality option missing for some streams

### ISSUE THREAD

**Issue by d07RiV** [lindstrm/twitcha#5]
Some streams only have the "Watch" option with no quality switch, even though the website does have it.

**Comment by lindstrm** [comment]
Can you give me an example of such stream?

**Comment by lindstrm** [comment]
Quality option is only available for partnered channels.

**Comment by d07RiV** [comment]
You mean non partnered streams (with ~100+ viewers) only have quality options when viewed via twitch.tv? I'm sure the streams in question had quality options on the website, I can provide an example next time I run across one.
